[2017-05-26 14:49:13.291] [ERROR] errorLogger - 
*************** error log start ***************
request method: GET
request originalUrl:  /api/user/getUser
request client ip:  ::1
request query:  {}
response time: 958
err name: SequelizeAccessDeniedError
err message: ER_ACCESS_DENIED_ERROR: Access denied for user ''@'localhost' (using password: NO)
err stack: SequelizeAccessDeniedError: ER_ACCESS_DENIED_ERROR: Access denied for user ''@'localhost' (using password: NO)
    at Handshake._callback (F:\koa2\koa2-demo\node_modules\sequelize\lib\dialects\mysql\connection-manager.js:82:20)
    at Handshake.Sequence.end (F:\koa2\koa2-demo\node_modules\mysql\lib\protocol\sequences\Sequence.js:85:24)
    at Handshake.ErrorPacket (F:\koa2\koa2-demo\node_modules\mysql\lib\protocol\sequences\Handshake.js:105:8)
    at Protocol._parsePacket (F:\koa2\koa2-demo\node_modules\mysql\lib\protocol\Protocol.js:280:23)
    at Parser.write (F:\koa2\koa2-demo\node_modules\mysql\lib\protocol\Parser.js:74:12)
    at Protocol.write (F:\koa2\koa2-demo\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (F:\koa2\koa2-demo\node_modules\mysql\lib\Connection.js:109:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at TCP.onread (net.js:561:20)
From previous event:
    at ConnectionManager.connect (F:\koa2\koa2-demo\node_modules\sequelize\lib\dialects\mysql\connection-manager.js:55:10)
    at ConnectionManager.<anonymous> (F:\koa2\koa2-demo\node_modules\sequelize\lib\dialects\abstract\connection-manager.js:247:43)
From previous event:
    at Promise.then (F:\koa2\koa2-demo\node_modules\sequelize\lib\promise.js:21:17)
    at Instance.save (F:\koa2\koa2-demo\node_modules\sequelize\lib\instance.js:579:6)
    at Model.create (F:\koa2\koa2-demo\node_modules\sequelize\lib\model.js:1813:6)
    at F:/koa2/koa2-demo/app/controllers/user.js:50:25
    at Generator.next (<anonymous>)
    at step (F:\koa2\koa2-demo\app\controllers\user.js:3:191)
    at F:\koa2\koa2-demo\app\controllers\user.js:3:437
    at F:\koa2\koa2-demo\app\controllers\user.js:3:99
    at exports.getUser (F:/koa2/koa2-demo/app/controllers/user.js:33:1)
    at dispatch (F:\koa2\koa2-demo\node_modules\koa-compose\index.js:44:32)
    at next (F:\koa2\koa2-demo\node_modules\koa-compose\index.js:45:18)
    at F:\koa2\koa2-demo\node_modules\koa-router\lib\router.js:345:16
    at dispatch (F:\koa2\koa2-demo\node_modules\koa-compose\index.js:44:32)
    at next (F:\koa2\koa2-demo\node_modules\koa-compose\index.js:45:18)
    at allowedMethods (F:\koa2\koa2-demo\node_modules\koa-router\lib\router.js:406:12)
    at dispatch (F:\koa2\koa2-demo\node_modules\koa-compose\index.js:44:32)
    at next (F:\koa2\koa2-demo\node_modules\koa-compose\index.js:45:18)
    at F:\koa2\koa2-demo\node_modules\koa-router\lib\router.js:345:16
    at dispatch (F:\koa2\koa2-demo\node_modules\koa-compose\index.js:44:32)
*************** error log end ***************

[2017-05-26 14:53:01.250] [ERROR] errorLogger - 
*************** error log start ***************
request method: GET
request originalUrl:  /api/user/getUser
request client ip:  ::1
request query:  {}
response time: 50
err name: SequelizeAccessDeniedError
err message: ER_ACCESS_DENIED_ERROR: Access denied for user ''@'localhost' (using password: NO)
err stack: SequelizeAccessDeniedError: ER_ACCESS_DENIED_ERROR: Access denied for user ''@'localhost' (using password: NO)
    at Handshake._callback (F:\koa2\koa2-demo\node_modules\sequelize\lib\dialects\mysql\connection-manager.js:82:20)
    at Handshake.Sequence.end (F:\koa2\koa2-demo\node_modules\mysql\lib\protocol\sequences\Sequence.js:85:24)
    at Handshake.ErrorPacket (F:\koa2\koa2-demo\node_modules\mysql\lib\protocol\sequences\Handshake.js:105:8)
    at Protocol._parsePacket (F:\koa2\koa2-demo\node_modules\mysql\lib\protocol\Protocol.js:280:23)
    at Parser.write (F:\koa2\koa2-demo\node_modules\mysql\lib\protocol\Parser.js:74:12)
    at Protocol.write (F:\koa2\koa2-demo\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (F:\koa2\koa2-demo\node_modules\mysql\lib\Connection.js:109:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at TCP.onread (net.js:561:20)
From previous event:
    at ConnectionManager.connect (F:\koa2\koa2-demo\node_modules\sequelize\lib\dialects\mysql\connection-manager.js:55:10)
    at ConnectionManager.<anonymous> (F:\koa2\koa2-demo\node_modules\sequelize\lib\dialects\abstract\connection-manager.js:247:43)
From previous event:
    at Promise.then (F:\koa2\koa2-demo\node_modules\sequelize\lib\promise.js:21:17)
    at Instance.save (F:\koa2\koa2-demo\node_modules\sequelize\lib\instance.js:579:6)
    at Model.create (F:\koa2\koa2-demo\node_modules\sequelize\lib\model.js:1813:6)
    at F:/koa2/koa2-demo/app/controllers/user.js:50:25
    at Generator.next (<anonymous>)
    at step (F:\koa2\koa2-demo\app\controllers\user.js:3:191)
    at F:\koa2\koa2-demo\app\controllers\user.js:3:437
    at F:\koa2\koa2-demo\app\controllers\user.js:3:99
    at exports.getUser (F:/koa2/koa2-demo/app/controllers/user.js:33:1)
    at dispatch (F:\koa2\koa2-demo\node_modules\koa-compose\index.js:44:32)
    at next (F:\koa2\koa2-demo\node_modules\koa-compose\index.js:45:18)
    at F:\koa2\koa2-demo\node_modules\koa-router\lib\router.js:345:16
    at dispatch (F:\koa2\koa2-demo\node_modules\koa-compose\index.js:44:32)
    at next (F:\koa2\koa2-demo\node_modules\koa-compose\index.js:45:18)
    at allowedMethods (F:\koa2\koa2-demo\node_modules\koa-router\lib\router.js:406:12)
    at dispatch (F:\koa2\koa2-demo\node_modules\koa-compose\index.js:44:32)
    at next (F:\koa2\koa2-demo\node_modules\koa-compose\index.js:45:18)
    at F:\koa2\koa2-demo\node_modules\koa-router\lib\router.js:345:16
    at dispatch (F:\koa2\koa2-demo\node_modules\koa-compose\index.js:44:32)
*************** error log end ***************

[2017-05-26 14:54:03.058] [ERROR] errorLogger - 
*************** error log start ***************
request method: GET
request originalUrl:  /api/user/getUser
request client ip:  ::1
request query:  {}
response time: 5
err name: userNotExist
err message: 用户不存在
err stack: userNotExist: 用户不存在
    at F:/koa2/koa2-demo/app/controllers/user.js:60:15
    at Generator.next (<anonymous>)
    at step (F:\koa2\koa2-demo\app\controllers\user.js:3:191)
    at F:\koa2\koa2-demo\app\controllers\user.js:3:437
    at F:\koa2\koa2-demo\app\controllers\user.js:3:99
    at exports.getUser (F:/koa2/koa2-demo/app/controllers/user.js:33:1)
    at dispatch (F:\koa2\koa2-demo\node_modules\koa-compose\index.js:44:32)
    at next (F:\koa2\koa2-demo\node_modules\koa-compose\index.js:45:18)
    at F:\koa2\koa2-demo\node_modules\koa-router\lib\router.js:345:16
    at dispatch (F:\koa2\koa2-demo\node_modules\koa-compose\index.js:44:32)
    at next (F:\koa2\koa2-demo\node_modules\koa-compose\index.js:45:18)
    at allowedMethods (F:\koa2\koa2-demo\node_modules\koa-router\lib\router.js:406:12)
    at dispatch (F:\koa2\koa2-demo\node_modules\koa-compose\index.js:44:32)
    at next (F:\koa2\koa2-demo\node_modules\koa-compose\index.js:45:18)
    at F:\koa2\koa2-demo\node_modules\koa-router\lib\router.js:345:16
    at dispatch (F:\koa2\koa2-demo\node_modules\koa-compose\index.js:44:32)
*************** error log end ***************

